### ISSUE TITLE
org-protocol-capture-html doesn't work on GitHub pages

### ISSUE THREAD

**Issue by mz-pdm** [alphapapa/org-protocol-capture-html#10]
For instance, if I select any region of the org-protocol-capture-html page (https://github.com/alphapapa/org-protocol-capture-html) and press my capturing button in Firefox, nothing happens.

**Comment by alphapapa** [comment]
Hi there!  Thanks for reporting this, but it works for me!  For example, if I visit that URL and select the first heading and first paragraph in the readme, then call the bookmarklet, Emacs pops up with an org-capture buffer with the selected text.  Or if I select some random parts of the file list, that works too.

What's probably happening is that you're selecting the whole page, or most of it, and that's exceeding the system's argument length limit.  This is an unfortunate limitation resulting from the way org-protocol works, where everything must be passed as a URL string as an argument to `emacsclient`.  According to [this](http://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument), the limit on Linux is typically about 128 KB.  And when you select part of a web page in a browser, the browser includes all the HTML tags, including ones that are irrelevant to the page structure, Pandoc, or Org, and all those extraneous tags add up.  

So in a case like that, you could either select less of the page, or you could try capturing it as plain-text with "regular" org-protocol, instead of capturing the HTML with this package.  Of course that would mean no conversion to Org with Pandoc, but there might be cases where that would be good enough.

I'm pretty sure that that's what's going on here, but if it's not, I'll be glad to help you if I can, if you can do some more troubleshooting.  :)

**Comment by mz-pdm** [comment]
Length of the selected text is not a problem. It doesn't work with any text of any length on any GitHub page I tried.
If you can instruct me how to investigate the problem, I can try to get more information. For now I looked at web console and the following message appears there when I press the bookmarklet button:

  Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://assets-cdn.github.com").

I've got no idea whether it is related to the problem or not.

**Comment by alphapapa** [comment]
I don't think that message is related to the problem.

So the bookmarklet works on any other web page, but not on GitHub?  I don't understand how that could be possible.  There is nothing about it that is specific to any site, and it works fine for me.

Maybe you have a Firefox add-on installed that is causing a problem somehow.  I'd recommend making a new, clean Firefox profile and testing the bookmarklet with that.  You could also test it in Chrome (using the Chrome bookmarklet)  and see if that works.  As far as I know, there must be something peculiar to your configuration causing the problem, since it works for me and other people.

**Comment by mz-pdm** [comment]
When I save the GitHub page and open it locally, it works and the error message is not present. But directly on GitHub it doesn't work. I created a new Firefox profile and it still doesn't work on GitHub. I use Firefox 45.2.0esr on Debian, but it didn't work for me even with some older Firefox version.
So the only clue is the error message. The error is logged when I invoke the capture so I guess it aborts the bookmarklet execution.

**Comment by alphapapa** [comment]
I googled for "firefox bookmarklet content security policy" and quickly found this:

https://bugzil.la/866522

Apparently GitHub is sending CSP headers that cause Firefox to disable bookmarklets.  There are some other links on that thread that you can follow if you want to dig into it more.

I can't explain why it works for me and not for you.  I'm using Firefox 47 with addons like NoScript and RequestPolicy, and who knows, maybe years ago I ran into this and messed with CSP settings or something.  The systems involved with Web security, HTML, JS, CSS, etc, have become extremely complex.

If you want to research it further, the links on that bug report should lead you in the right direction, and hopefully to a solution.  There is no bug here in this project--it's a matter of the way GitHub sends CSP headers and the way Firefox applies them to all bookmarklets by default.

If you do find a solution, please let me know so I can mention it in the instructions.

I'm sorry that I can't be more help.  Good luck.
